//using try and catch any exception type of problem resolve

console.log("hello");
console.log("hii");
try{                  //it throw the errors 
  console.log(a);
}catch{               //it catch the throw errors and print throgh catch
  console.log("an error occured ");
}
console.log("byee");